<a href="https://colab.research.google.com/github/Carsoboss/pytorch_fundamentals/blob/main/00_PyTorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

If you have a question: https://github.com/mrdbourke/pytorch-deep-learning/discussions



In [ ]:
import torch
print(torch.__version__)

2.1.0+cu121


## Introductio to Tensors

## Creating Tensors

Pytorch tensors are creatued using 'torch.Tensor()=https://pytorch.org/docs/stable/tensors.html

In [ ]:
## scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# Get tensor back aa Python int
scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
#checking for dimensions
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3, 4],
                        [3, 6, 9, 5],
                       [3, 6, 9, 5]
                        ]])
TENSOR

tensor([[[1, 2, 3, 4],
         [3, 6, 9, 5],
         [3, 6, 9, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 4])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3, 4],
        [3, 6, 9, 5],
        [3, 6, 9, 5]])

### Random Tensors

Why random Tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers then adjust those numbers to better represent the data.



In [ ]:
# Create a random tensor of size or shape (3, 4)

In [ ]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.1171, 0.6295, 0.6589, 0.4580],
        [0.7450, 0.3339, 0.1267, 0.3105],
        [0.7369, 0.9779, 0.7779, 0.6722]])

In [ ]:
random_tensor.ndim, random_tensor.shape

(2, torch.Size([3, 4]))

In [ ]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channel
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
### Create a tensor of all zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
random_tensor.dtype

torch.float32

### Create a range of tensors and tensors-like

In [ ]:
# Use torch.range. and get deprecated message, use torch.arange()
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
stepwise = torch.arange(start=0, end = 10, step=.1)
stepwise

tensor([0.0000, 0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000,
        0.9000, 1.0000, 1.1000, 1.2000, 1.3000, 1.4000, 1.5000, 1.6000, 1.7000,
        1.8000, 1.9000, 2.0000, 2.1000, 2.2000, 2.3000, 2.4000, 2.5000, 2.6000,
        2.7000, 2.8000, 2.9000, 3.0000, 3.1000, 3.2000, 3.3000, 3.4000, 3.5000,
        3.6000, 3.7000, 3.8000, 3.9000, 4.0000, 4.1000, 4.2000, 4.3000, 4.4000,
        4.5000, 4.6000, 4.7000, 4.8000, 4.9000, 5.0000, 5.1000, 5.2000, 5.3000,
        5.4000, 5.5000, 5.6000, 5.7000, 5.8000, 5.9000, 6.0000, 6.1000, 6.2000,
        6.3000, 6.4000, 6.5000, 6.6000, 6.7000, 6.8000, 6.9000, 7.0000, 7.1000,
        7.2000, 7.3000, 7.4000, 7.5000, 7.6000, 7.7000, 7.8000, 7.9000, 8.0000,
        8.1000, 8.2000, 8.3000, 8.4000, 8.5000, 8.6000, 8.7000, 8.8000, 8.9000,
        9.0000, 9.1000, 9.2000, 9.3000, 9.4000, 9.5000, 9.6000, 9.7000, 9.8000,
        9.9000])

In [ ]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=stepwise)
ten_zeros

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.])

### Tensor datatypes

In [ ]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                              dtype= None, #what datatype is the tensor (e.g 16 or 32 bit floating points)
                               device="cpu", # What device is your tensor on
                               requires_grad=False,) # whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:
1.  Tensors not right datatypes
2. Tensors not right shape
3.  Tensors not on the right device

In [ ]:
float_16_tensor = float_32_tensor.type(torch.half)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor.dtype

torch.float16

In [ ]:
### How to multiply tensors of different data types when you have an error

new_float_16 = float_16_tensor.to(dtype=torch.float32)
new_float_16 * float_32_tensor


tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor =torch.tensor([3, 6, 9], dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [ ]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors

1.  Tensors not right datatypes - to get datatype from a tensor, can use 'tensor.dtype'
2.  Tensors not right shape -to get shape from a tensor, can use 'tensor.shape'
3.  Tensors not on the right device - to get device from a tensor, can use tensor.device

In [ ]:
# Create a tensor
some_tensor = torch.rand(3, 4, dtype = torch.half, device = "cuda" )
some_tensor

tensor([[0.8486, 0.4773, 0.1947, 0.9526],
        [0.9785, 0.5542, 0.1425, 0.1801],
        [0.2023, 0.8271, 0.7026, 0.1399]], device='cuda:0',
       dtype=torch.float16)

In [ ]:
# find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

tensor([[0.8486, 0.4773, 0.1947, 0.9526],
        [0.9785, 0.5542, 0.1425, 0.1801],
        [0.2023, 0.8271, 0.7026, 0.1399]], device='cuda:0',
       dtype=torch.float16)
Datatype of tensor: torch.float16
Shape of tensor: torch.Size([3, 4])
Device of tensor: cuda:0


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [ ]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [ ]:
# Subtract 10
tensor -10

tensor([-9, -8, -7])

In [ ]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor, 10)

tensor([11, 12, 13])

In [ ]:
torch.divide(tensor, 10)

tensor([0.1000, 0.2000, 0.3000])

### Matrix multiplication

Two main ways of perfoming multiplication in neural networks and deep learning:

Element-wise multiplication
Matrix multiplication (dot product)

The size of the product is the size of the column vector of the first vector and the row of the second vector.

There are two main rules for matrix multiplication:
1.  The **inner dimensions** must match:
* '(3,2) @ (3,2)' won't work
* '(2,3) @ (3,2)' will work
* '(3,2) @ (2,3)' will work
2.  The resulting matrix hs the shape of the **outer dimensions**:
* '(2, 3) @ (3, 2)' -> '(2, 2)'
* '(3,2) @ (2,3)' -> '(3,3)'

In [ ]:
torch.matmul(torch.rand(3, 2), torch.rand (2,3))

tensor([[0.7539, 0.5792, 0.5854],
        [0.2654, 0.2418, 0.2204],
        [0.4867, 0.7215, 0.5098]])

In [ ]:
# Element wise multiplicaiton
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
# Matrix multiplicaiton
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
# Matrix multiplication by hand

tensor[0]*tensor[0] + tensor[1]*tensor[1] + tensor[2]*tensor[2]

tensor(14)

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value


CPU times: user 503 µs, sys: 838 µs, total: 1.34 ms
Wall time: 3.32 ms


tensor(14)

In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 34 µs, sys: 9 µs, total: 43 µs
Wall time: 45.8 µs


tensor(14)

### One of the most common errors in deep learning: shape errors

In [ ]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

# torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul (it's an alias for writing less code)


To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**

A **transpose** switches the axes or dimesnsions of a given tensor.

In [ ]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [ ]:
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [ ]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [ ]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Origional shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tesnor_A = {tensor_A.shape} (same shape as above), tesnor_B.T = [tensor_B.T]")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output: \n")
output = torch.mm(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput Shape: {output.shape}")



Origional shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tesnor_A = torch.Size([3, 2]) (same shape as above), tesnor_B.T = [tensor_B.T]
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output: 

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output Shape: torch.Size([3, 3])


## Finding the min, maz, mean, sum, etc (tensor aggregation)

In [ ]:
# Create a tensor
x =torch.arange(1, 100, 10)
x, x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [ ]:
# Find the min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [ ]:
# Find the max
torch.max(x), x.max()

(tensor(91), tensor(91))

In [ ]:
# Find the mean - note: the torch.mean() function requires a tensor of float332 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [ ]:
# Find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

In [ ]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
## Finding the position in tesnor that has the minimum value with agmin() -> reutrns index position of target tensor where the minimum value occurs
x.argmin()

tensor(0)

In [ ]:
x[0]

tensor(1)

In [ ]:
# Find the position in tensor that has the maximum balue with argmax()
x.argmax()

tensor(9)

## Reshaping, stacking, squeezing, and unsqueezing

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the origional tensor
* Stacking -combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all '1' dimensions from a tensor
* Unsqueeze - add a '1' dimension to a target tensor
* Permut -Return a view of the input with dimensions permuted (swapped) in a certain way


In [ ]:
# Let's create a tensor
import torch
x = torch.arange(1, 10)
x, x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
print(x_reshaped)
print(x_reshaped.shape)
print(F"\n or \n")
# or
x_reshape = x.reshape(3, 3)
x_reshape, x_reshape.shape
# It just has to be compatible with the amout of elements

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])
torch.Size([1, 9])

 or 



(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 torch.Size([3, 3]))

In [ ]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [ ]:
# Changing z changes x (because a view of a tensor shares the same memory as the original)
z[:, 0] = 5
z, x

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]), tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]))

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim =1)
x_stacked

tensor([[5, 5, 5, 5],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [4, 4, 4, 4],
        [5, 5, 5, 5],
        [6, 6, 6, 6],
        [7, 7, 7, 7],
        [8, 8, 8, 8],
        [9, 9, 9, 9]])

In [ ]:
# V stack and H stack
x_stacked = torch.vstack([x, x, x, x])
print(x_stacked)
x_stacked = torch.hstack([x, x, x, x])
print(f"\n{x_stacked}")

tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9]])

tensor([5, 2, 3, 4, 5, 6, 7, 8, 9, 5, 2, 3, 4, 5, 6, 7, 8, 9, 5, 2, 3, 4, 5, 6,
        7, 8, 9, 5, 2, 3, 4, 5, 6, 7, 8, 9])


In [ ]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])
New shape: torch.Size([9])


In [ ]:
# torch.unqueeze() - adds a single dimensinon to a target tensor at a specific dim (dimension)
print(f"Previous targe: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous targe: tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])
Previous shape: torch.Size([9])

New tensor: tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]])
New shape: torch.Size([1, 9])


In [ ]:
# torch.permute - rearranges the dimensions fo a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3)) #[height, width, color_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0
print(f"Previous shape {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [ ]:
x_original

tensor([[[0.6048, 0.0984, 0.4335],
         [0.2802, 0.6117, 0.9479],
         [0.1717, 0.4046, 0.8611],
         ...,
         [0.4593, 0.7087, 0.0687],
         [0.3530, 0.1177, 0.0924],
         [0.2151, 0.4121, 0.0373]],

        [[0.7090, 0.8627, 0.4549],
         [0.6218, 0.3852, 0.5746],
         [0.7600, 0.1069, 0.2058],
         ...,
         [0.5250, 0.4367, 0.0190],
         [0.3890, 0.3184, 0.1772],
         [0.8823, 0.3949, 0.7129]],

        [[0.7929, 0.9974, 0.7970],
         [0.1796, 0.9165, 0.1603],
         [0.7588, 0.1422, 0.0105],
         ...,
         [0.1043, 0.5089, 0.2793],
         [0.0318, 0.0736, 0.8530],
         [0.2157, 0.2399, 0.2254]],

        ...,

        [[0.6967, 0.3299, 0.7443],
         [0.4230, 0.2710, 0.6761],
         [0.9796, 0.7177, 0.4638],
         ...,
         [0.7196, 0.1495, 0.6322],
         [0.7314, 0.3288, 0.5518],
         [0.3498, 0.1014, 0.3344]],

        [[0.9857, 0.1941, 0.0791],
         [0.1593, 0.9818, 0.6262],
         [0.

In [ ]:
x_permuted

tensor([[[0.6048, 0.2802, 0.1717,  ..., 0.4593, 0.3530, 0.2151],
         [0.7090, 0.6218, 0.7600,  ..., 0.5250, 0.3890, 0.8823],
         [0.7929, 0.1796, 0.7588,  ..., 0.1043, 0.0318, 0.2157],
         ...,
         [0.6967, 0.4230, 0.9796,  ..., 0.7196, 0.7314, 0.3498],
         [0.9857, 0.1593, 0.0183,  ..., 0.2999, 0.1400, 0.5472],
         [0.1768, 0.7359, 0.2017,  ..., 0.1083, 0.0962, 0.7087]],

        [[0.0984, 0.6117, 0.4046,  ..., 0.7087, 0.1177, 0.4121],
         [0.8627, 0.3852, 0.1069,  ..., 0.4367, 0.3184, 0.3949],
         [0.9974, 0.9165, 0.1422,  ..., 0.5089, 0.0736, 0.2399],
         ...,
         [0.3299, 0.2710, 0.7177,  ..., 0.1495, 0.3288, 0.1014],
         [0.1941, 0.9818, 0.9802,  ..., 0.0245, 0.6354, 0.0399],
         [0.1349, 0.5498, 0.3494,  ..., 0.2737, 0.2406, 0.0843]],

        [[0.4335, 0.9479, 0.8611,  ..., 0.0687, 0.0924, 0.0373],
         [0.4549, 0.5746, 0.2058,  ..., 0.0190, 0.1772, 0.7129],
         [0.7970, 0.1603, 0.0105,  ..., 0.2793, 0.8530, 0.

## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy.

In [ ]:
# Create a tensor
import torch
x= torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# Let's index on the middle bracket (dim=1)
x[0, 0]

tensor([1, 2, 3])

In [ ]:
# Let's index on the most ineer bracket (last dimension)
x[0, 2, 2]

tensor(9)

In [ ]:
# You can also use ":" to select "all" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [ ]:
# Get all values of 0th dimensions but only index 1 of 2nd dimensions
x[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
# Get all values of the 0 dimension but only the 1 index vlaue of the 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [ ]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [ ]:
# Index on x to return 9
print(x[0, 2, 2])
# Index on x to return 3, 6, 9
print(x[:, :, 2])

tensor(9)
tensor([[3, 6, 9]])


## PyTorch tensors and NumPy

Numpy is a pupular scientific Python numerical computing library.

And because of this,, PyTorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor ->'roch.from_numpy(ndarray)'
* PyTorch ttensor -> NumPy -> torch.Tensor.numpy()

In [ ]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # warning: when converting from numpy -> pytorch,, pytorch reflects numpy's default datatype of float64 unless specified otherwise
array, tensor


(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Change the balue of array, what will this do to 'tensor'?
array = array +1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
numpy_tensor.dtype

dtype('float32')

In [ ]:
# Change the tensor, what happens to 'numpy_tensor'?
tensor = tensor +1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducability (trying to take the random out of random)

In short how a neural network learns:

' start with random numbers -> tensor operations -> update random numbers to try to make them better representations of the data -> again -> again -> again... '

To reduce the randomness in neural netwrorks and PyTorch comes the concept of a **random seed**.

Essentially what the random seed does is "flavor" the randomness.

In [ ]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.7152, 0.7593, 0.0612, 0.7166],
        [0.1637, 0.8655, 0.7767, 0.3682],
        [0.6546, 0.1269, 0.9261, 0.5860]])
tensor([[0.3141, 0.1057, 0.8829, 0.3567],
        [0.8286, 0.4889, 0.9601, 0.7392],
        [0.1372, 0.6929, 0.7192, 0.6300]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# Let's make some random but reproducible tensors
import torch

# Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


from os.path import supports_unicode_filenames
## Running tensors and PyTorch objects on GPUs (and making faster computations)

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working beind the scenes

from sre_constants import GROUPREF_UNI_IGNORE
### 1.  Getting a GPU

1. Easiest - Use Google Colab for a free GPU.numpy_tensor
2. Use your onw GPU - takes a little bit of setup and requires the investment of purchasing a GPU
3. Use cloud computing - GCP, AWS, Azure, these services allow you to rent computers on the cloud and access them
